gathrapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('emptycart/', views.emptycart, name='empty'),
    path('success/', views.success, name='success'),
    path('accounts/signup/', views.signup, name='signup'),

    path('products/', views.ProductList.as_view(), name="product_index"),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products/create/', views.ProductCreate.as_view(), name='product_create'),
    path('products/<int:pk>/update/', views.ProductUpdate.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),

    path('causes/', views.cause_index, name="cause_index"),
    path('causes/<int:pk>/', views.CauseDetail.as_view(), name='cause_detail'),
    path('causes/create/', views.CauseCreate.as_view(), name="cause_create"),
    path('causes/<int:pk>/update/', views.CauseUpdate.as_view(), name="cause_update"),
    path('causes/<int:pk>/delete/', views.CauseDelete.as_view(), name="cause_delete"),

    path('profile/<int:user_id>/', views.user_detail, name='user_detail'),

    path('addcart/<int:product_id>/', views.add_cart, name='add_cart'),

    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/<int:order_id>/update/', views.order_form, name='order_update'),
    path('cart/<int:order_id>/', views.order_confirm, name='order_confirm'),

    path('cart/<int:order_id>/empty', views.order_empty, name='order_empty'),

    path('products/<int:product_id>/add_photo/', views.add_product_photo, name='add_product_photo'),
    path('causes/<int:cause_id>/add_photo/', views.add_cause_photo, name='add_cause_photo'),
    # path('users/<int:user_id>/add_photo/', views.add_user_photo, name='add_user_photo'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

SIZES = (
    ('XS', 'Extra Small'),
    ('S', 'Small'),
    ('M', 'Medium'),
    ('L', 'Large'),
    ('XL', 'Extra Large'),
)

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
	('OW', 'Outerwear'),
	('SW', 'Sweatshirt'),
)

class Cause(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    cause_type = models.CharField(max_length=100)
    proceeds = models.IntegerField()
    url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField(max_length=250)
    size = models.CharField(max_length=100)
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default=CATEGORY_CHOICES[0][0]
    )
    cause = models.ForeignKey(Cause, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Order(models.Model):
    product = models.ManyToManyField(Product)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

class CausePhoto(models.Model):
    url = models.CharField(max_length=200)
    cause = models.ForeignKey(Cause, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cause_id: {self.cause_id} @{self.url}"

class ProductPhoto(models.Model):
    url = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for product_id: {self.product_id} @{self.url}"

class UserPhoto(models.Model):
    url = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for user_id: {self.user_id} @{self.url}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    causes = models.ManyToManyField(Cause)
    purchased_items = models.ManyToManyField(Order)

    def __str__(self):
        return self.user.username


# User model
    # username
    # first_name
    # last_name
    # email
    # password
    # groups
    # is_superuser(boolean)


# class ShippingAddress(models.Model):
#     customer = models.ForeignKey(Profile, on_delete=models.SET_NULL)
#     order = models.ForeignKey(Cart, on_delete=models.SET_NULL)
#     address = models.CharField(max_length=200)
#     city = models.CharField(max_length=200)
#     state = models.CharField(max_length=200)
#     zipcode = models.CharField(max_length=200)
#     date_added = models.DateTimeField(auto_now_add=True)

#     def __str_(self):
#         return self.address

main_app/forms.py
from django.forms import ModelForm
from .models import Order

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['product','ordered']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required #@login_required  -- add this to functions
from django.contrib.auth.mixins import LoginRequiredMixin #LoginRequiredMixin, -- add this in CBV parameter
from django.utils import timezone
from django.db.models.signals import post_save
from .models import Product, Cause, Profile, User, Order, ProductPhoto, CausePhoto, UserPhoto
from .forms import OrderForm
import uuid
import boto3

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'learning-catcollector-aws-s3'


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def emptycart(request):
  return render(request, 'empty.html')

def success(request):
  return render(request, 'success.html')


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class ProductList(ListView):
  queryset = Product.objects.filter(Q(size='Small') | Q(size='7') )

def product_detail(request, product_id):
  product = Product.objects.get(id=product_id)
  other_prod = Product.objects.filter(Q(name=product.name) & ~Q(size=product.size))
  return render(request, 'main_app/product_detail.html', {'product': product, 'other_prod': other_prod})

class ProductCreate(LoginRequiredMixin, CreateView):
  model = Product
  fields = '__all__'

class ProductUpdate(LoginRequiredMixin, UpdateView):
  model = Product
  fields = '__all__'

class ProductDelete(LoginRequiredMixin, DeleteView):
  model = Product
  success_url = '/products/'

def cause_index(request):
  causes = Cause.objects.all()
  return render(request, 'main_app/cause_list.html', {'cause_list': causes})

class CauseDetail(DetailView):
  model = Cause

class CauseCreate(LoginRequiredMixin, CreateView):
  model = Cause
  fields = '__all__'

class CauseUpdate(LoginRequiredMixin, UpdateView):
  model = Cause
  fields = '__all__'

class CauseDelete(LoginRequiredMixin, DeleteView):
  model = Cause
  success_url = '/causes/'

@login_required
def user_detail(request, user_id):
  user = User.objects.get(id=user_id)
  return render(request, 'main_app/user_detail.html', {'user': user})

@login_required
def add_cart(request, product_id):
  order_query = Order.objects.filter(user=request.user, ordered=False)
  product1 = Product.objects.get(id=product_id)
  if order_query.exists():
    order = order_query[0]
    if order.product.filter(id = product_id).exists():
      pass
    else:
      order.product.add(product1)
  else:
    ordered_date = timezone.now()
    order = Order.objects.create(user=request.user, ordered_date=ordered_date)
    order.product.add(product1)
  return render(request, 'main_app/order_detail.html', {'order': order})

@login_required
def cart_detail(request):
  not_ordered = request.user.order_set.filter(ordered=False).exists()
  if not_ordered:
    order = Order.objects.get(user=request.user, ordered=False)
    return render(request, 'main_app/order_detail.html', {'order': order})
  else:
    return render(request, 'empty.html') 

@login_required
def order_form(request, order_id):
  order = Order.objects.get(id=order_id)
  return render(request, 'main_app/order_form.html', {'order': order})

@login_required
def order_confirm(request, order_id):
  order_query = Order.objects.filter(user=request.user, ordered=False)
  order = order_query[0]
  order.ordered = True
  order.save()
  return render(request, 'success.html')

@login_required
def order_empty(request, order_id):
  order = Order.objects.get(id=order_id)
  for prod in order.product.all():
    order.product.remove(prod.id)
  return redirect('product_index')

@login_required
def add_product_photo(request, product_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = ProductPhoto(url=url, product_id=product_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('product_detail', product_id=product_id)

@login_required
def add_cause_photo(request, cause_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = CausePhoto(url=url, cause_id=cause_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('cause_detail', pk=cause_id)

main_app/templates/main_app/cart_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cart</h1>

<div class="row">
    <div class="col s6">
      <table class="striped">
        <thead>
          <tr><th>Item</th><th>Size</th><th>Quantity</th><th>Price</th></tr>
        </thead>
        <tbody>
          {% for orderproduct in cart.item_set.all %}
              <tr>
                <td><a href="{% url 'product_detail' orderproduct.item %}">Image</a></td>
                <td>{{ orderproduct.size }}</a></td>
                <td>{{ orderproduct.order_quantity }}</a></td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  </div>
  {% endblock %}

main_app/templates/main_app/cause_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete Cause</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn">
    <a href="{% url 'cause_detail' cause.id %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/cause_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cause Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
        {% for photo in cause.causephoto_set.all %}
          <img class="responsive-img" src="{{photo.url}}">
        {% endfor %}
        {% if user.is_superuser %}
            <form action="{% url 'add_cause_photo' cause.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
              {% csrf_token %}
              <input type="file" name="photo-file">
              <br><br>
              <input type="submit" class="btn" value="Upload Photo">
            </form>
          {% endif %}
    </div>
  </div>
  <div class="col s6">
    <h4>{{ cause.name }}</h4>
    <p>Description: {{ cause.description }}</p>
    <p>Type: {{ cause.type }}</p>
    <p>Proceeds Raised to Date: {{ cause.proceeds }}</p>
    <p>Learn More about the Cause: {{ cause.url }}</p>
    <hr>
    <p class="tabletitle"><strong>Products that support this cause</strong></p>
    <table>
      <tbody>
        {% for product in cause.product_set.all %}
            <tr>
              <td><a href="{% url 'product_detail' product.id %}">
                {% for photo in product.productphoto_set.all %}
                  <img id="listphoto" class="responsive-img" src="{{photo.url}}">
                {% endfor %}
              </a>
              </td>
              <td><a href="{% url 'product_detail' product.id %}">{{product.name}}</a></td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/cause_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Cause</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/cause_list.html
{% extends 'base.html' %}
{% block content %}

<div class="buffer">
    <div class="row center-align">
        <div class="col center-align">
            <h1 >View All Partners</h1>
        </div>
    </div>
</div>

<div class="row">
    {% for cause in cause_list %}
    <a href="{% url 'cause_detail' cause.id %}">
        <div class="col s9 m6 l4">
        <h5>{{ cause.name }}</h5>
        <div class="card-img">
            {% for photo in cause.causephoto_set.all %}
            <img class="responsive-img" src="{{photo.url}}">
            {% endfor %}
        </div>
        <p>Description: {{ cause.description }}</p>
        <hr>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

main_app/templates/main_app/order_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Empty Cart</h1>

  <h4>Are you sure you want to empty cart?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn">
    <a href="{% url 'order_detail' order.id %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/order_form.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col s6 offset-s3 center-align">
        <h2>Confirm Purchase</h2>
        <form action="{% url 'order_confirm' order.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Confirm" class="btn">
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/order_summary.html
{% extends 'base.html' %}
{% block content %}

<h1>Cause Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cart }}</span>
        <p>Quantity: {{ cart__items.order_quantity }}</p>
        
      </div>
      <div class="card-action">
        <a href="{% url 'cause_update' cause.id %}">Edit</a>
        <a href="{% url 'cause_delete' cause.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/orderproduct_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cause Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ orderproduct.item.name }}</span>
        <p>Quantity: {{ orderproduct.order_quantity }}</p>
        <p>Size: {{ orderproduct.size }}</p>
        
      </div>
      <div class="card-action">
        <a href="{% url 'cause_update' cause.id %}">Edit</a>
        <a href="{% url 'cause_delete' cause.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/orderproduct_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Cart</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/product_detail.html
{% extends 'base.html' %}
{% block content %}


<h1>Product Details</h1>


<div class="row">
  <div class="col s6 offset-s1">
    <div class="card">
          {% for photo in product.productphoto_set.all %}
            <img class="responsive-img" src="{{photo.url}}">
          {% endfor %}
          {% if user.is_superuser %}
            <form action="{% url 'add_product_photo' product.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
              {% csrf_token %}
              <input type="file" name="photo-file">
              <br><br>
              <input type="submit" class="btn" value="Upload Photo">
            </form>
          {% endif %}
    </div>
  </div>
  <div class="col s3">
    <h4>{{ product.name }}</h4>
    <p>Price: {{ product.price }}</p>
    <p>Description: {{ product.description }}</p>
      <a class="waves-effect waves-light pink darken-1 btn-small">{{ product.size }}</a>
      {% for prod in other_prod %}
      <a class="waves-effect waves-light pink darken-3 btn-small" href="{% url 'product_detail' prod.id %}">{{ prod.size }}</a>
      {% endfor %}
      <br><br>
      <form action="{% url 'add_cart' product.id %}" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn black" value="Add to Cart">
      </form>
  </div>

</div>
{% endblock %}

main_app/templates/main_app/product_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Product</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/product_list.html
{% extends 'base.html' %}
{% block content %}

<div class="row center-align">
    <div class="col center-align">
        <h1>Browse All Products</h1>
    </div>
</div>

<div class="row">
    {% for product in product_list %}
    <a href="{% url 'product_detail' product.id %}">
        <div class="col s9 m6 l4">
            <h5>{{ product.name }}</h5>
            <p>${{ product.price }}</p>
            <div class="card-img">
                {% for photo in product.productphoto_set.all %}
                <img class="responsive-img" src="{{photo.url}}">
                {% endfor %}
            </div>
            <hr>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

main_app/templates/main_app/user_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Profile Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ profile.user.username }}</span>
        <p>PROFILE PIC</p>
      </div>
    </div>
  </div>
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        {% for cause in profile.causes_set.all %}
        <ul>
          <li>{{ cause }}</li>
        </ul>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        {% for order in user.profile.causes_set.all %}
      </div>
    </div>
  </div>
</div>

{% endblock %}